version: "{branch} {build}"

image:
  - Visual Studio 2022

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - SET GRADLE_OPTS=-Xmx1024m
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble --stacktrace --no-daemon

test_script:
  - gradlew.bat check funcTest --stacktrace --no-daemon --continue -Pcompatibility

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk17
    #Regression tests with different Gradle versions only on JDK 17
    PITEST_REGRESSION_TESTS: quick
#  - JAVA_HOME: C:\Program Files\Java\jdk21
#    PITEST_REGRESSION_TESTS: latestOnly

matrix:
  fast_finish: false
