version: "{branch} {build}"
image: Visual Studio 2022

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - SET GRADLE_OPTS=-Xmx1024m
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble --stacktrace

test_script:
  - gradlew.bat check funcTest --stacktrace --continue -Pcompatibility

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk17

matrix:
  fast_finish: false
